FROM node:20.20-alpine3.23

# Add non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Install dev only necessary tools
RUN apk add --no-cache netcat-openbsd wget

WORKDIR /app

# Create dirs and fix ownership
RUN mkdir -p node_modules dist logs\
  && chown -R appuser:appgroup /app

# Copy files with correct ownership
COPY --chown=appuser:appgroup package*.json ./
COPY --chown=appuser:appgroup prisma ./prisma/
COPY --chown=appuser:appgroup tsconfig*.json ./
COPY --chown=appuser:appgroup scripts ./scripts/
COPY --chown=appuser:appgroup nodemon.json ./
COPY --chown=appuser:appgroup public ./public

# Switch to non-root user
USER appuser

RUN npm install

EXPOSE 8080

CMD ["npx", "nodemon"] 

